-- MySQL Script generated by MySQL Workbench
-- Thu Nov  3 23:16:16 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TPO
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TPO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TPO` DEFAULT CHARACTER SET utf8 ;
USE `TPO` ;

-- -----------------------------------------------------
-- Table `TPO`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TPO`.`country` ;

CREATE TABLE IF NOT EXISTS `TPO`.`country` (
  `code` VARCHAR(3) NOT NULL,
  `name` VARCHAR(145) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TPO`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TPO`.`city` ;

CREATE TABLE IF NOT EXISTS `TPO`.`city` (
  `code` INT NOT NULL,
  `name` VARCHAR(145) NOT NULL,
  `country_code` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`code`, `country_code`),
  INDEX `fk_city_country_idx` (`country_code` ASC) VISIBLE,
  CONSTRAINT `fk_city_country`
    FOREIGN KEY (`country_code`)
    REFERENCES `TPO`.`country` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TPO`.`street`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TPO`.`street` ;

CREATE TABLE IF NOT EXISTS `TPO`.`street` (
  `Street_name` VARCHAR(150) NOT NULL,
  `Street_number` INT NOT NULL,
  `city_code` INT NOT NULL,
  `country_code` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`Street_name`, `Street_number`, `city_code`, `country_code`),
  INDEX `fk_street_city1_idx` (`city_code` ASC, `country_code` ASC) VISIBLE,
  CONSTRAINT `fk_street_city1`
    FOREIGN KEY (`city_code` , `country_code`)
    REFERENCES `TPO`.`city` (`code` , `country_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TPO`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TPO`.`customer` ;

CREATE TABLE IF NOT EXISTS `TPO`.`customer` (
  `username` VARCHAR(10) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(85) NOT NULL,
  `surname` VARCHAR(85) NOT NULL,
  `company_name` VARCHAR(85) NULL,
  `tel_num` VARCHAR(45) NOT NULL,
  `street_Street_name` VARCHAR(150) NOT NULL,
  `street_Street_number` INT NOT NULL,
  `street_city_code` INT NOT NULL,
  `street_country_code` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`username`),
  INDEX `fk_customer_street1_idx` (`street_Street_name` ASC, `street_Street_number` ASC, `street_city_code` ASC, `street_country_code` ASC) VISIBLE,
  CONSTRAINT `fk_customer_street1`
    FOREIGN KEY (`street_Street_name` , `street_Street_number` , `street_city_code` , `street_country_code`)
    REFERENCES `TPO`.`street` (`Street_name` , `Street_number` , `city_code` , `country_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TPO`.`parcel_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TPO`.`parcel_status` ;

CREATE TABLE IF NOT EXISTS `TPO`.`parcel_status` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TPO`.`parcel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TPO`.`parcel` ;

CREATE TABLE IF NOT EXISTS `TPO`.`parcel` (
  `id` VARCHAR(8) NOT NULL,
  `parcel_status_id` INT NOT NULL,
  `sender` VARCHAR(10) NOT NULL,
  `recipient` VARCHAR(10) NOT NULL,
  `weight` DOUBLE NOT NULL,
  `height` INT NOT NULL,
  `width` INT NOT NULL,
  `depth` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_parcel_customer1_idx` (`sender` ASC) VISIBLE,
  INDEX `fk_parcel_customer2_idx` (`recipient` ASC) VISIBLE,
  INDEX `fk_parcel_parcel_status1_idx` (`parcel_status_id` ASC) VISIBLE,
  CONSTRAINT `fk_parcel_customer1`
    FOREIGN KEY (`sender`)
    REFERENCES `TPO`.`customer` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parcel_customer2`
    FOREIGN KEY (`recipient`)
    REFERENCES `TPO`.`customer` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parcel_parcel_status1`
    FOREIGN KEY (`parcel_status_id`)
    REFERENCES `TPO`.`parcel_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TPO`.`branch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TPO`.`branch` ;

CREATE TABLE IF NOT EXISTS `TPO`.`branch` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `street_Street_name` VARCHAR(150) NOT NULL,
  `street_Street_number` INT NOT NULL,
  `street_city_code` INT NOT NULL,
  `street_country_code` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_branch_street1_idx` (`street_Street_name` ASC, `street_Street_number` ASC, `street_city_code` ASC, `street_country_code` ASC) VISIBLE,
  CONSTRAINT `fk_branch_street1`
    FOREIGN KEY (`street_Street_name` , `street_Street_number` , `street_city_code` , `street_country_code`)
    REFERENCES `TPO`.`street` (`Street_name` , `Street_number` , `city_code` , `country_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TPO`.`staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TPO`.`staff` ;

CREATE TABLE IF NOT EXISTS `TPO`.`staff` (
  `username` VARCHAR(10) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(85) NOT NULL,
  `surname` VARCHAR(85) NOT NULL,
  `branch_id` INT NOT NULL,
  PRIMARY KEY (`username`),
  INDEX `fk_staff_branch1_idx` (`branch_id` ASC) VISIBLE,
  CONSTRAINT `fk_staff_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `TPO`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TPO`.`job_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TPO`.`job_type` ;

CREATE TABLE IF NOT EXISTS `TPO`.`job_type` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TPO`.`job_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TPO`.`job_status` ;

CREATE TABLE IF NOT EXISTS `TPO`.`job_status` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TPO`.`job`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TPO`.`job` ;

CREATE TABLE IF NOT EXISTS `TPO`.`job` (
  `id` INT NOT NULL,
  `date_created` DATETIME NOT NULL,
  `date_completed` DATETIME NULL,
  `job_type_id` INT NOT NULL,
  `job status_id` INT NOT NULL,
  `staff_username` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_job_job_type1_idx` (`job_type_id` ASC) VISIBLE,
  INDEX `fk_job_job status1_idx` (`job status_id` ASC) VISIBLE,
  INDEX `fk_job_staff1_idx` (`staff_username` ASC) VISIBLE,
  CONSTRAINT `fk_job_job_type1`
    FOREIGN KEY (`job_type_id`)
    REFERENCES `TPO`.`job_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_job status1`
    FOREIGN KEY (`job status_id`)
    REFERENCES `TPO`.`job_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_staff1`
    FOREIGN KEY (`staff_username`)
    REFERENCES `TPO`.`staff` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TPO`.`job_packet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TPO`.`job_packet` ;

CREATE TABLE IF NOT EXISTS `TPO`.`job_packet` (
  `job_id` INT NOT NULL,
  `parcel_id` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`job_id`, `parcel_id`),
  INDEX `fk_job_packet_parcel1_idx` (`parcel_id` ASC) VISIBLE,
  CONSTRAINT `fk_job_packet_job1`
    FOREIGN KEY (`job_id`)
    REFERENCES `TPO`.`job` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_packet_parcel1`
    FOREIGN KEY (`parcel_id`)
    REFERENCES `TPO`.`parcel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
